/* ENUM - USADO PARA VALORES CONSTANTES E IMUTAVEIS (IMUTAVEL: QUE NAO MUDA) */

public enum DiaDaSemana { //

	/* O ENUM SERIA A MESMA COISA WUE ESCREVER ALGO COMO: private static FINAL tipoDoAtributo nome 
	 * COMO VISTO ANTES, O FINAL INDICA QUE AQUELA EH A FORMA FINAL DO ATRIBUTO */
	
	SEGUNDA,
	TERCA,
	QUARTA,
	QUINTA,
	SEXTA,
	SABADO,
	DOMINGO
}
